<aside class="grid_3 sidebar sidebar-left">
<div class="box-link">
<header class="widget-title"><div class="left-divider"></div>
<h2 style=" font-size:16px !important; font-weight: bold !important;">Order Support</h2>
<div class="right-divider"></div></header>
<ul class="navigation-left">
<li><a href="shipping_information">Shipping Information</a></li>
<li><a href="return_cancellation">Cancellation and returns</a></li>
<li><a href="faq">FAQs</a></li>
<li><a href="corporate-deal-enquiry">Corporate Deals</a></li>
</ul></div>
<div class="img-head-txt">Have Question?</div>
<img style="float:right;" src="<?php echo $this->getSkinUrl('images/talk2us.png'); ?>" alt=""/></div>			
    </aside>
<div class="grid_9 col-main">
<div class="page-title"><h1 style="vertical-align:bottom"><img src="<?php echo $this->getSkinUrl('images/bulk.png'); ?>" alt=""/> CORPORATE DEALS - ENQUIRY</h1></div>

TO Purchase a large quantity of a single item or multiple items, you can fill in the below from and let us know about your request.<br><br>
We will reach out to you soon.
<div class="form-corporate">
<ul>
<li><input placeholder="Name" type="text" name=""></li> 
<li><input placeholder="Company Name" type="text" name=""></li> 
<li><input placeholder="City" type="text" name=""></li> 
<li><input placeholder="Address" type="text" name=""></li> 
<li><input placeholder="Contact Number/Mobile Number" type="text" name=""></li> 
<li style="line-height:32px"><input style="width:80px; margin-right:25px; float:left;" placeholder="Extension" type="text" name=""> (optional)</li> 
<li><input placeholder="Email" type="text" name=""></li> 
<li style="width:100%;"><b>Order Details</b></li> 
<li style="width:100%;"><textarea style="height:130px;" name=""></textarea></li> 
<li style="width:100%;"><input class="btn-sub" type="button" name="" value="Submit"></li> 
</ul>

</div>
</div>