<?php

/**

 * @author		Sashas

* @category    Sashas

* @package     Sashas_OrderSuccessPage

* @copyright   Copyright (c) 2013 Sashas IT Support Inc. (http://www.sashas.org)

* @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)

*/
?>
<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="order-success" style="width:100%; float:right;">
<div class="page-title title-buttons order-info-title">
    <h1><?php echo $this->__('Your Order #%s (%s)', $_order->getRealOrderId(),$this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
    <button type="button" title="Continue Shopping" class="button btn-continue" onclick="setLocation('http://testing.buynbrag.com/')"><span><span>Continue Shopping</span></span></button>
</div>
 
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box box-right">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Method') ?></h2>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box box-left">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
</div>
<div style="clear:both"></div>