<?php if($this->getCurrencyCount() > 1):
//print_r($this->getCurrencies()); 
?>
<div class="form-language">
    <label for="custom-currency-selector"><?php //echo $this->__('Your Currency:') ?></label>
    <select class="pretty_sb" onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
        <option value="<?php echo $this->getSwitchCurrencyUrl($_code)?>"
            <?php if($_code == $this->getCurrentCurrencyCode()): ?>
                selected="SELECTED"
            <?php endif; ?>>
            <?php echo Mage::app()->getLocale()->currency( $_code )->getSymbol().'&nbsp;&nbsp;&nbsp;&nbsp;'.$_code ?>
        </option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>